pypi-typeguard: Autospec creation for update from version 3.0.2 to version 4.0.0
Alex Grönholm (51):
      Refactored instrumentation to use the annotations in the checks directly
      Added support for type checking against nonlocal classes
      Removed obsolete commented out code
      Fixed test failures on Python 3.7
      Removed leftover reference to CallMemo
      Fixed support for nested forward references
      Fixed check_type() not always returning the passed value
      Fixed suppress_type_checks() not ending suppression on exception
      Improved support for `if TYPE_CHECKING:`
      Added support for using `suppress_type_checks()` as a decorator
      Added release date
      Fixed TestSelf.test_return_valid() not actually calling the method
      Generate the optimization suffix from typeguard version
      Don't recurse into calls in AnnotationTransformer
      Copy locations when parsing strings in AnnotationTransformer
      Fixed typed variable positional/keyword arguments causing compilation errors on Python < 3.9
      Fixed compilation error when a type annotation contains a type guarded by `if TYPE_CHECKING:`
      Moved _ast imports to be done from the proper module
      Added release date
      Fixed typing.Literal subscript contents being evaluated as forward references
      Fixed resolution of forward references in type aliases
      Updated notes on forward references regarding instrumented code
      Updated pre-commit modules and fixed new mypy errors
      Added release date
      Fixed subscripts of unimportable types not being handled correctly
      Fixed instrumentation mutating function annotations on py < 3.9
      Fixed Concatenate raising TypeError in check_callable()
      Corrected issue reference in dummymodule.never_called()
      Reversed the order of "black" and "ruff"
      Bumped the minimum mypy version
      Fixed AttributeError when variable arg annotation is on the ignore list
      Don't try to check against types shadowed by argument names
      Skip checking PEP 604 unions where Any is one of the elements
      Don't check unions where any element is Any (or an ignored type)
      Fixed checking against a generic NewType
      Added release date
      Fixed Optional without subscript being used for type checks
      Added InstrumentationWarning to the public API
      Fixed TypeError when trying to check against a naked str forward reference
      Fixed wrong self_type being assigned to the memo in the `__new__()` method
      Switched to publishing to PyPI as a trusted publisher
      Added contribution documentation
      Skip type checks where the type names are shadowed by local variables
      Switch to the official coveralls action
      Made `@typechecked` a no-op in optimized mode (#350)
      Added release date
      Use the proper environment for release
      Fixed AST transformations potentially leaving "if" bodies empty
      Don't try to parse the second argument of Annotated as a forward reference
      Added release date
      Declared the latest RC as final

Anton Agestam (1):
      Made check_type independent of global config and added support for overrides in `@typechecked` (#317)

Danie-1 (1):
      Update README.rst import hook example to be compatible with 3.0.0 (#321)

Marcel Telka (1):
      Call pytest indirectly (#328)

Tolker-KU (1):
      Fix TypedDict checker for odd types (#322)

pre-commit-ci[bot] (4):
      [pre-commit.ci] pre-commit autoupdate (#323)
      [pre-commit.ci] pre-commit autoupdate (#329)
      [pre-commit.ci] pre-commit autoupdate (#344)
      [pre-commit.ci] pre-commit autoupdate (#351)